embedding:
  type: "OpenAIEmbeddings"  # Options: "HuggingFaceBgeEmbeddings", "OpenAIEmbeddings"
  
  # Configuration for HuggingFaceBgeEmbeddings
  HuggingFaceBgeEmbeddings:
    model_name: "BAAI/bge-m3"
    model_kwargs:
      trust_remote_code: True
      device: "cuda"  # Options: "cuda", "cpu"
    encode_kwargs:
      normalize_embeddings: True
  
  # Configuration for OpenAIEmbeddings
  OpenAIEmbeddings:
    api_key: "your_openai_api_key_here"
    model_name: "text-embedding-ada-002"
    model_kwargs:
      temperature: 0.7
      max_tokens: 2048
chroma:
  collection_name: "Sun"

  Sun:
    collection_name : collection_name
    collection_path : collection_name